version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: /Code-Tester.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  web-client:
    build:
      context: web-client
    ports:
      - "3000:3000"

  docs:
    build:
      context: docs
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

networks:
  mynetwork:
    driver: bridge
